# Generated by Django 3.2.18 on 2023-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('link', models.TextField()),
                ('images', models.TextField()),
                ('school', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('money', models.IntegerField()),
                ('value', models.FloatField()),
                ('machine', models.CharField(max_length=200)),
            ],
        ),
    ]
